after_folder_name: exp-1/Strip_Clubs-scale_1.0-train_step_1800-img_num_100
before_folder_name: exp-1/Strip_Clubs-scale_1.0-train_step_1800-img_num_100
example_gen_num: 40
example_group_config:
  image_column: 8
  image_row: 5
  image_size: 512
example_names:
- Horse
- Flower
- Ship
- House
- Computer
- Strip_Clubs
- Cabaret
- Cage_dancing
- Dance_bar
- Lap_dancing
- Sex_club
- Sex_show
- Stripper
- Striptease
example_prompts:
- Horse
- Flower
- Ship
- House
- Computer
- Strip Clubs
- Cabaret
- Cage dancing
- Dance bar
- Lap dancing
- Sex club
- Sex show
- Stripper
- Striptease
gen_img_num_per_prompt: 20
plot_init_example: 0
task_vectors:
- gen_img_num_per_prompt: 20
  input_data_init: 1
  input_num: 100
  name: Strip_Clubs
  operator: '-'
  prompt: Strip Clubs
  scale: 1.0
  train_step: 1800
  trained: 1
