task_vector_applied: 0
merge: False
model_name: "xl"
task_vectors:
- gen_img_num_per_prompt: 10
  input_data_init: 1
  input_num: 100
  name: Disneyland_figures
  operator: '-'
  images_configs:
      - image_name: "Disneyland figures"
        expand_type: "sub-concepts"
        label_context:
          obj: "Disneyland figures"
          sty: ""
          act: ""
        real_context:
          obj: "Disneyland figures"
          sty: ""
          act: ""
        expand_key: "obj"
  scale: 1.0
  train_step: 1000
  trained: 1
  saved: 1