folder_name: /test_kill
img_gen_num: 20
img_names: [kill]
img_prompts: ["Create an image of a man kills a soldier with a knife."]
gen_img_num_per_prompt: 1
unet_path: "/root/autodl-fs/unet_backup/unet_original_diffusion_pytorch_model.bin"