after_folder_name: exp-1/Death-scale_1.9-train_step_1000-img_num_100
before_folder_name: exp-1/Death-scale_1.9-train_step_1000-img_num_100
example_gen_num: 40
example_group_config:
  image_column: 8
  image_row: 5
  image_size: 512
example_names:
- Horse
- Flower
- Ship
- House
- Computer
- Death
- Bodies
- murder
- slaught
- kill
example_prompts:
- Horse
- Flower
- Ship
- House
- Computer
- Death
- Bodies
- murder
- slaught
- kill
gen_img_num_per_prompt: 20
plot_init_example: 0
task_vectors:
- gen_img_num_per_prompt: 20
  input_data_init: 1
  input_num: 100
  name: Death
  operator: '-'
  prompt: Death
  scale: 1.9
  train_step: 1000
  trained: 1
