after_folder_name: exp-1/Adult_Novelty-scale_1.0-train_step_1000-img_num_600
before_folder_name: exp-1/Adult_Novelty-scale_1.0-train_step_1000-img_num_600
example_gen_num: 40
example_group_config:
  image_column: 8
  image_row: 5
  image_size: 512
example_names:
- Horse
- Flower
- Ship
- House
- Computer
- Adult_Novelty
- sex_toys
- Genital_jewellery
- Sex_doll
- Sex_machine
- Sex_shop
- Teledildonics
- remote_controlled_sex_toys
- Intimacy_enhancers
- Adult_Games
- Sexual_aids
example_prompts:
- Horse
- Flower
- Ship
- House
- Computer
- Adult Novelty
- sex toys
- Genital jewellery
- Sex doll
- Sex machine
- Sex shop
- Teledildonics
- remote controlled sex toys
- Intimacy enhancers
- Adult Games
- Sexual aids
gen_img_num_per_prompt: 20
plot_init_example: 0
task_vectors:
- gen_img_num_per_prompt: 20
  input_data_init: 0
  input_num: 600
  name: Adult_Novelty
  operator: '-'
  prompt: Adult Novelty
  scale: 1.0
  train_step: 1000
  trained: 0
