example_gen_num: 0
example_group_config:
  image_column: 0
  image_row: 0
  image_size: 512
example_names: []
example_prompts: []
plot_init_example: 0
task_vectors:
- input_num: 100
  name: 11-Weapons-1-Firearms
  operator: '-'
  prompt: Firearms
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-2-Armaments
  operator: '-'
  prompt: Armaments
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-3-Artillery
  operator: '-'
  prompt: Artillery
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-4-Ammunition
  operator: '-'
  prompt: Ammunition
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-5-Arsenal
  operator: '-'
  prompt: Arsenal
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-6-Blades
  operator: '-'
  prompt: Blades
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-7-Swords
  operator: '-'
  prompt: Swords
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-8-Knives
  operator: '-'
  prompt: Knives
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-9-Guns
  operator: '-'
  prompt: Guns
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-10-Rifles
  operator: '-'
  prompt: Rifles
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-12-Explosives
  operator: '-'
  prompt: Explosives
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-13-Munitions
  operator: '-'
  prompt: Munitions
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-15-Missiles
  operator: '-'
  prompt: Missiles
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-16-Grenades
  operator: '-'
  prompt: Grenades
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-17-Crossbows
  operator: '-'
  prompt: Crossbows
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 11-Weapons-18-Bows
  operator: '-'
  prompt: Bows
  scale: 1.0
  train_step: 1000
  trained: 0
