example_gen_num: 0
example_group_config:
  image_column: 0
  image_row: 0
  image_size: 512
example_names: []
example_prompts: []
plot_init_example: 0
task_vectors:
- input_num: 100
  name: 2-Adult_Novelty-2-sex_toys
  operator: '-'
  prompt: sex toys
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 2-Adult_Novelty-3-Genital_jewellery
  operator: '-'
  prompt: Genital jewellery
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 2-Adult_Novelty-4-Sex_doll
  operator: '-'
  prompt: Sex doll
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 2-Adult_Novelty-5-Sex_machine
  operator: '-'
  prompt: Sex machine
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 2-Adult_Novelty-6-Sex_shop
  operator: '-'
  prompt: Sex shop
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 2-Adult_Novelty-7-Teledildonics
  operator: '-'
  prompt: Teledildonics
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 2-Adult_Novelty-10-Adult_Games
  operator: '-'
  prompt: Adult Games
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 2-Adult_Novelty-11-Sexual_aids
  operator: '-'
  prompt: Sexual aids
  scale: 1.0
  train_step: 1000
  trained: 0
