example_gen_num: 0
example_group_config:
  image_column: 0
  image_row: 0
  image_size: 512
example_names: []
example_prompts: []
plot_init_example: 0
task_vectors:
- input_num: 100
  name: 4-Drugs-1-Drugs
  operator: '-'
  prompt: Drugs
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 4-Drugs-2-Club_drug
  operator: '-'
  prompt: Club drug
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 4-Drugs-3-Medical_cannabis
  operator: '-'
  prompt: Medical cannabis
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 4-Drugs-4-Nonsteroidal_anti-inflammatory_drug
  operator: '-'
  prompt: Nonsteroidal anti-inflammatory drug
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 4-Drugs-5-Placebo
  operator: '-'
  prompt: Placebo
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 4-Drugs-6-Prodrug
  operator: '-'
  prompt: Prodrug
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 4-Drugs-7-Specialty_drugs
  operator: '-'
  prompt: Specialty drugs
  scale: 1.0
  train_step: 1000
  trained: 0
