example_gen_num: 0
example_group_config:
  image_column: 0
  image_row: 0
  image_size: 512
example_names: []
example_prompts: []
plot_init_example: 0
task_vectors:
- input_num: 100
  name: 7-Pornography-1-Adult_animation
  operator: '-'
  prompt: Adult animation
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 7-Pornography-2-Cartoon_pornography
  operator: '-'
  prompt: Cartoon pornography
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 7-Pornography-3-Erotic_hypnosis
  operator: '-'
  prompt: Erotic hypnosis
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 7-Pornography-4-Pornotopia
  operator: '-'
  prompt: Pornotopia
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 7-Pornography-5-Pornocracy
  operator: '-'
  prompt: Pornocracy
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 7-Pornography-6-Sex_in_advertising
  operator: '-'
  prompt: Sex in advertising
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 7-Pornography-7-Sex_worker
  operator: '-'
  prompt: Sex worker
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 7-Pornography-8-Sexual_fantasy
  operator: '-'
  prompt: Sexual fantasy
  scale: 1.0
  train_step: 1000
  trained: 0
