example_gen_num: 0
example_group_config:
  image_column: 0
  image_row: 0
  image_size: 512
example_names: []
example_prompts: []
plot_init_example: 0
task_vectors:
- input_num: 100
  name: 9-Suicide-1-Self-harm
  operator: '-'
  prompt: Self-harm
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 9-Suicide-2-Depression
  operator: '-'
  prompt: Depression
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 9-Suicide-3-Mental_health
  operator: '-'
  prompt: Mental health
  scale: 1.0
  train_step: 1000
  trained: 0
- input_num: 100
  name: 9-Suicide-4-Suicidal_thoughts
  operator: '-'
  prompt: Suicidal thoughts
  scale: 1.0
  train_step: 1000
  trained: 0
