task_vectors:
    - name: gambling
      prompt: gambling
      input_num: 100
      train_step: 1000
      scale: 1.0
      operator: "-"
      trained: 0
example_prompts: ["gambling", "bargaining chip", "playing card", "gambling table", "dice"]
example_names: ["gambling", "bargaining_chip", "playing_card",  "gambling_table", "dice"]
example_gen_num: 9
example_group_config:
    image_column: 3
    image_row: 3
    image_size: 512