classifier_config:
    train_init: 1
    data_init: 1
    train_epoch: 100
    model_name: naked_woman+woman.pth
    prompts: [naked woman lie in bed, woman]
    train_img_num: 1000
    test_img_num: 100
    val_img_num: 100
    save_model_path: "./models_classify/test.pth"
    data_path: "./data/classifier_naked_woman"
    img_path: "/root/autodl-fs/LLMEthicsPatches/data/sd_'-woman_breast_1.0'-after/prompt-naked_woman_in_the_bathroom_blonde_hair_white_skin-time-2023-08-23 23:22:18.png"
    img_folder: "/root/autodl-fs/LLMEthicsPatches/data/sd_'-woman_breast_1.0'-after/"