after_folder_name: exp-1/Suicide-scale_1.0-train_step_1000-img_num_200
before_folder_name: exp-1/Suicide-scale_1.0-train_step_1000-img_num_200
example_gen_num: 40
example_group_config:
  image_column: 8
  image_row: 5
  image_size: 512
example_names:
- Horse
- Flower
- Ship
- House
- Computer
- Suicide
- Self-harm
- Depression
- Mental_health
- Suicidal_thoughts
example_prompts:
- Horse
- Flower
- Ship
- House
- Computer
- Suicide
- Self-harm
- Depression
- Mental health
- Suicidal thoughts
gen_img_num_per_prompt: 20
plot_init_example: 0
task_vectors:
- gen_img_num_per_prompt: 20
  input_data_init: 0
  input_num: 200
  name: Suicide
  operator: '-'
  prompt: Suicide
  scale: 1.0
  train_step: 1000
  trained: 0
